//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsApp.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTipoLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BTipoLogin()
        {
            this.Logueo = new HashSet<Logueo>();
        }
    
        public int TipoLoginID { get; set; }
        public string CodigoTipoLogin { get; set; }
        public string NombreTipoLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logueo> Logueo { get; set; }
    }
}
