//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsApp.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudenAppHelperDBEntities : DbContext
    {
        public StudenAppHelperDBEntities()
            : base("name=StudenAppHelperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BTipoDocumento> BTipoDocumento { get; set; }
        public virtual DbSet<BTipoLogin> BTipoLogin { get; set; }
        public virtual DbSet<LoginKey> LoginKey { get; set; }
        public virtual DbSet<LoginKeyHistorial> LoginKeyHistorial { get; set; }
        public virtual DbSet<Logueo> Logueo { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usurio> Usurio { get; set; }
    }
}
