//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsApp.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usurio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usurio()
        {
            this.Logueo = new HashSet<Logueo>();
        }
    
        public int IdUsuario { get; set; }
        public int TipoDocumento { get; set; }
        public string DocumentoUsuario { get; set; }
        public string NombrePrimero { get; set; }
        public string NombreSegundo { get; set; }
        public string ApellidoPrimer { get; set; }
        public string ApellidoSegundo { get; set; }
        public int TipoUsuario { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public bool esActivo { get; set; }
    
        public virtual BTipoDocumento BTipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logueo> Logueo { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
