//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginKey()
        {
            this.LoginKeyHistorial = new HashSet<LoginKeyHistorial>();
            this.Logueo = new HashSet<Logueo>();
        }
    
        public int LoginKeyID { get; set; }
        public string loginUser { get; set; }
        public string loginPass { get; set; }
        public string loginKey1 { get; set; }
        public Nullable<System.DateTime> fechaAcceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginKeyHistorial> LoginKeyHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logueo> Logueo { get; set; }
    }
}
