//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginKey()
        {
            this.Login = new HashSet<Login>();
            this.LoginKeyHistorial = new HashSet<LoginKeyHistorial>();
        }
    
        public int LoginKeyId { get; set; }
        public string LoginNick { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
        public string LoginPass { get; set; }
        public string LoginKey1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginKeyHistorial> LoginKeyHistorial { get; set; }
    }
}
