//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginId { get; set; }
        public int LoginTypeId { get; set; }
        public Nullable<int> LoginKeyId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual BLoginType BLoginType { get; set; }
        public virtual LoginKey LoginKey { get; set; }
        public virtual User User { get; set; }
    }
}
