//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginKeyHistorial
    {
        public int LoginKeyHistorialID { get; set; }
        public Nullable<int> LoginKeyID { get; set; }
        public Nullable<int> idUsuarioRegistra { get; set; }
        public string LoginAnterior { get; set; }
        public string loginPassAnterior { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual LoginKey LoginKey { get; set; }
    }
}
