//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int TagId { get; set; }
        public int TagType { get; set; }
        public int TopicId { get; set; }
        public int MatterId { get; set; }
        public int ContentId { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual TagType TagType1 { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
