//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntityModel.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudenAppHelperDBEntities : DbContext
    {
        public StudenAppHelperDBEntities()
            : base("name=StudenAppHelperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BDocumentType> BDocumentType { get; set; }
        public virtual DbSet<BLoginType> BLoginType { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<LoginKey> LoginKey { get; set; }
        public virtual DbSet<LoginKeyHistorial> LoginKeyHistorial { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Content> Content { get; set; }
        public virtual DbSet<ContentType> ContentType { get; set; }
        public virtual DbSet<Matter> Matter { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagType> TagType { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
